DROP DATABASE IF EXISTS bd_leitura;
CREATE DATABASE bd_leitura;

USE bd_leitura;

DROP TABLE IF EXISTS livros;
CREATE TABLE livros (
		id 							INTEGER PRIMARY KEY AUTO_INCREMENT,
		titulo 						VARCHAR(200) NOT NULL,
		autor 						VARCHAR(100) NOT NULL,
		editora	 					VARCHAR(100) NOT NULL,
		genero						VARCHAR(50) NOT NULL,
        sinopse						VARCHAR(5000) NOT NULL
        
);

DROP TABLE IF EXISTS comentario;
CREATE TABLE comentario (
		id 							INTEGER PRIMARY KEY AUTO_INCREMENT,
		livros_id					INTEGER,
        livro_titulo				VARCHAR(50) NOT NULL,
        nome 						VARCHAR(250) NOT NULL,
		comentario					VARCHAR(2000) NOT NULL,
		email 						VARCHAR(50) NOT NULL,
        
        FOREIGN KEY livrosFK (livros_id) REFERENCES livros(ID) ON UPDATE CASCADE,
        CONSTRAINT CHK_EmailValidate CHECK(email REGEXP "[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?")
);



DROP TABLE IF EXISTS pedido;
CREATE TABLE pedido (
		id 							INTEGER PRIMARY KEY AUTO_INCREMENT,
		livro 						VARCHAR(200) NOT NULL,
		genero 						VARCHAR(100) NOT NULL,
		nome	 					VARCHAR(100) NOT NULL,
		email						VARCHAR(50)
        
);






DELIMITER $$

 
DROP PROCEDURE IF EXISTS Genero $$
    CREATE PROCEDURE Genero (IN getGenero TEXT)

	BEGIN
		IF getGenero = 'Romance' THEN
			SELECT titulo,
				   autor,		
     			   editora,
                   genero,
        		   sinopse		 

			FROM livros WHERE genero LIKE 'Romance' ORDER BY titulo ASC;

        ELSEIF getGenero = 'Thriller' THEN
			SELECT titulo,
				   autor,		
     			   editora,
                   genero,
        		   sinopse	
			FROM livros WHERE genero LIKE 'Thriller' ORDER BY titulo ASC;
            
		ELSEIF getGenero = 'Aventura' THEN
			SELECT titulo,
				   autor,		
     			   editora,
                   genero,
        		   sinopse	
			FROM livros WHERE genero LIKE 'Aventura' ORDER BY titulo ASC;
		
        ELSEIF getGenero = 'Ficção Cientifica' THEN
			SELECT titulo,
				   autor,		
     			   editora,
                   genero,
        		   sinopse	
			FROM livros WHERE genero LIKE 'Ficção Cientifica' ORDER BY titulo ASC;
		
        ELSEIF getGenero = 'Comédia' THEN
			SELECT titulo,
				   autor,		
     			   editora,
                   genero,
        		   sinopse	
			FROM livros WHERE genero LIKE 'Comédia' ORDER BY titulo ASC;
            
		ELSEIF getGenero = 'Terror' THEN
			SELECT titulo,
				   autor,		
     			   editora,
                   genero,
        		   sinopse	
			FROM livros WHERE genero LIKE 'Terror' ORDER BY titulo ASC;
            
		ELSEIF getGenero = 'Fantasia' THEN
			SELECT titulo,
				   autor,		
     			   editora,
                   genero,
        		   sinopse	
			FROM livros WHERE genero LIKE 'Fantasia' ORDER BY titulo ASC;
            
		ELSEIF getGenero = 'Drama' THEN
			SELECT titulo,
				   autor,		
     			   editora,
                   genero,
        		   sinopse	
			FROM livros WHERE genero LIKE 'Drama' ORDER BY titulo ASC;

        ELSE
			SELECT titulo,
				   autor,		
     			   editora,			
        		   genero,		
        		   sinopse	
			FROM livros ORDER BY titulo ASC;

        END IF;
	END$$
    
    INSERT INTO livros 
(titulo, autor, editora, genero, sinopse)

VALUES

("A Biblioteca da noite", "Gillian Flynn", "Bertrand Brasil", "Romance", "Aos 35 anos, Nora Seed é uma mulher cheia de talentos e poucas conquistas. Arrependida das escolhas que fez no passado, ela vive se perguntando o que poderia ter acontecido caso tivesse vivido de maneira diferente. Após ser demitida e seu gato ser atropelado, Nora vê pouco sentido em sua existência e decide colocar um ponto final em tudo. Porém, quando se vê na Biblioteca da Meia-Noite, Nora ganha uma oportunidade única de viver todas as vidas que poderia ter vivido. Neste lugar entre a vida e a morte, e graças à ajuda de uma velha amiga, Nora pode, finalmente, se mudar para a Austrália, reatar relacionamentos antigos – ou começar outros –, ser uma estrela do rock, uma glaciologista, uma nadadora olímpica... enfim, as opções são infinitas. Mas será que alguma dessas outras vidas é realmente melhor do que a que ela já tem? Em A Biblioteca da Meia-Noite, Nora Seed se vê exatamente na situação pela qual todos gostaríamos de poder passar: voltar no tempo e desfazer algo de que nos arrependemos. Diante dessa possibilidade, Nora faz um mergulho interior viajando pelos livros da Biblioteca da Meia-Noite até entender o que é verdadeiramente importante na vida e o que faz, de fato, com que ela valha a pena ser vivida."),
("A paciente silenciosa", "Alex Michaelides", "Record", "Thriller", "Alicia Berenson tinha uma vida perfeita. Ela era uma pintora famosa casada com um fotógrafo bem-sucedido e morava numa área nobre de Londres que dá para o parque de Hampstead Heath. Certa noite, Gabriel, seu marido, voltou tarde para casa depois de um ensaio para a Vogue, e de repente a vida de Alicia mudou completamente... Alicia tinha 33 anos quando deu cinco tiros no rosto do marido, e ela nunca mais disse uma palavra. A recusa de Alicia a falar ou a dar qualquer explicação transforma essa tragédia doméstica em algo muito maior - um mistério que atrai a atenção do público e aumenta ainda mais a fama da pintora. Entretanto, enquanto seus quadros passam a ser mais valorizados que nunca, ela é levada para o Grove, um hospital psiquiátrico judiciário na zona norte de Londres. Enquanto isso, Theo Faber é um psicoterapeuta forense que espera há muito tempo por uma oportunidade de trabalhar com Alicia. Ele tem certeza de que é a pessoa certa para lidar com o caso. No entanto, sua determinação para fazê-la falar e desvendar o mistério de por que ela atirou no marido o arrasta para um caminho tortuoso que sugere que as raízes do silêncio de Alicia são muito mais profundas do que ele jamais poderia imaginar."),
("Jantar secreto", "Raphael Montes", "Companhia das Letras", "Thriller", "Um grupo de jovens deixa uma pequena cidade no Paraná para viver no Rio de Janeiro. Eles alugam um apartamento em Copacabana e fazem o possível para pagar a faculdade e manter vivos seus sonhos de sucesso na capital fluminense. Mas o dinheiro está curto e o aluguel está vencido. Para sair do buraco e manter o apartamento, os amigos adotam uma estratégia heterodoxa: arrecadar fundos por meio de jantares secretos, divulgados pela internet para uma clientela exclusiva da elite carioca. A partir daí, eles se envolvem em uma espiral de crimes, descobrem uma rede de contrabando de corpos, matadouros clandestinos e grã-finos excêntricos, e levam ao limite uma índole perversa que jamais imaginaram existir em cada um deles."),
("Uma mulher no escuro", "Raphael Montes", "Companhia das Letras", "Thriller", "Victoria Bravo tinha quatro anos quando um homem invadiu sua casa e matou sua família a facadas, pichando seus rostos com tinta preta. Única sobrevivente, ela agora é uma jovem solitária e tímida, com pesadelos frequentes e sérias dificuldades para se relacionar. Seu refúgio é ficar em casa e observar a vida alheia pelas janelas do apartamento onde mora, na Lapa, Rio de Janeiro. Mas o passado bate à sua porta, e ela não sabe mais em quem pode confiar. Obrigada a enfrentar sua própria tragédia, Victoria embarca em uma jornada de amadurecimento e descoberta que a levará a zonas obscuras, mas também revelará as possibilidades do amor. Um psiquiatra, um amigo feito pela internet e um possível namorado — qual dos três homens está usando tudo o que sabe para aterrorizar a vida de Vic? E o que afinal ele quer com ela? Na literatura nacional, Raphael Montes é unanimidade quando se trata de livros de suspense. Uma mulher no escuro traz sua primeira protagonista feminina e confirma o autor como um dos mais originais da atualidade — além de deixar o leitor intrigado do começo ao fim."),
("Dias perfeitos", "Raphael Montes", "Companhia das Letras", "Thriller", "O protagonista do livro é Téo, um jovem e solitário estudante de medicina que divide seu tempo entre cuidar da mãe paraplégica e dissecar cadáveres nas aulas de anatomia. Num churrasco a que vai com a mãe contrariado, Téo conhece Clarice, uma jovem de espírito livre que sonha tornar-se roteirista de cinema. Clarice está escrevendo um road movie de nome Dias perfeitos. O texto ainda está cru, mas ela já sabe a história que quer contar: as desventuras de três amigas que viajam de carro pelo país em busca de experiências amorosas. Téo fica viciado em Clarice: quer desvendar aquela menina diferente de todas que conheceu. Começa, então, a se aproximar de forma insistente. Diante das seguidas negativas, opta por uma atitude extrema: desfere um golpe na cabeça dela e, ato contínuo, sequestra a garota. Elabora então um plano para conquistá-la: coloca-a sedada no banco carona de seu carro e inicia uma viagem pelas estradas do Rio de Janeiro - a mesma viagem feita pelas personagens do roteiro de Clarice. Passando por cenários oníricos, entre os quais um chalé em Teresópolis administrado por anões e uma praia deserta e paradisíaca em Ilha Grande, o casal estabelece uma rotina insólita: Téo a obriga a escrever a seu lado e está pronto para sedá-la ou prendê-la à menor tentativa de resistência. Clarice oscila entre momentos de desespero e resignação, nos quais corresponde aos delírios conjugais de seu sequestrador. O efeito é tão mais perturbador quanto maior a naturalidade de Téo. Ele fala com calma, planeja os atos com frieza e justifica suas decisões com lógica impecável. A capacidade do autor de explorar uma psique doentia é impressionante - e o mergulho psicológico não impede que o livro siga um ritmo eletrizante, digno dos melhores thrillers da atualidade."),
("Outsider", "Stephen King", "Suma", "Terror", "O corpo de um menino de onze anos é encontrado abandonado no parque de Flint City, brutalmente assassinado. Testemunhas e impressões digitais apontam o criminoso como uma das figuras mais conhecidas da cidade ― Terry Maitland, treinador da Liga Infantil de beisebol, professor de inglês, casado e pai de duas filhas. O detetive Ralph Anderson não hesita em ordenar uma prisão rápida e bastante pública, fazendo com que em pouco tempo toda a cidade saiba que o Treinador T é o principal suspeito do crime. Maitland tem um álibi, mas Anderson e o promotor público logo têm amostras de DNA para corroborar a acusação. O caso parece resolvido. Mas conforme a investigação se desenrola, a história se transforma em uma montanha-russa, cheia de tensão e suspense. Terry Maitland parece ser uma boa pessoa, mas será que isso não passa de uma máscara? A aterrorizante resposta é o que faz desta uma das histórias mais perturbadoras de Stephen King."),
("O iluminado", "Stephen King", "Suma", "Terror", "O lugar perfeito para recomeçar, é o que pensa Jack Torrance ao ser contratado como zelador para o inverno. Hora de deixar para trás o alcoolismo, os acessos de fúria, os repetidos fracassos. Isolado pela neve com a esposa e o filho, tudo o que Jack deseja é um pouco de paz para se dedicar à escrita. Mas, conforme o inverno se aprofunda, o local paradisíaco começa a parecer cada vez mais remoto... e mais sinistro. Forças malignas habitam o Overlook, e tentam se apoderar de Danny Torrance, um garotinho com grandes poderes sobrenaturais. Possuir o menino, no entanto, se mostra mais difícil do que esperado. Então os espíritos resolvem se aproveitar das fraquezas do pai... Um dos livros mais assustadores de todos os tempos, O iluminado é um clássico de Stephen King."),
("Doutor Sono", "Stephen King", "Suma", "Terror", "Mais de trinta anos depois, Stephen King revela a seus leitores o que aconteceu a Danny Torrance, o garoto no centro de O iluminado, depois de sua terrível experiência no Overlook Hotel. Em Doutor Sono, King dá continuidade a essa história, contando a vida de Dan, agora um homem de meia-idade, e Abra Stone, uma menina de 12 anos com um grande poder. Assombrado pelos habitantes do Overlook Hotel, onde passou um ano terrível de sua infância, Dan ficou à deriva por décadas, desesperado para se livrar do legado de alcoolismo e violência do pai. Finalmente, ele se instala em uma cidade de New Hampshire, onde encontra abrigo em uma comunidade do Alcoólicos Anônimos que o apoia e um emprego em uma casa de repouso, onde seu poder remanescente da iluminação fornece o conforto final para aqueles que estão morrendo. Ajudado por um gato que prevê a morte dos pacientes, ele se torna o Doutor Sono.Então Dan conhece Abra Stone, uma menina com um dom espetacular, a iluminação mais forte que já se viu. Ela desperta os demônios de seu passado e Dan se vê envolvido em uma batalha pela alma e sobrevivência dela. Uma guerra épica entre o bem e o mal, uma sangrenta e gloriosa história que vai emocionar os milhões de fãs de O Iluminado e satisfazer os leitores de King."),
("It: A coisa", "Stephen King", "Suma", "Terror", "Durante as férias de 1958, em uma pacata cidadezinha chamada Derry, um grupo de sete amigos começa a ver coisas estranhas. Um conta que viu um palhaço, outro que viu uma múmia. Finalmente, acabam descobrindo que estavam todos vendo a mesma coisa: um ser sobrenatural e maligno que pode assumir várias formas. É assim que Bill, Beverly, Eddie, Ben, Richie, Mike e Stan enfrentam a Coisa pela primeira vez. Quase trinta anos depois, o grupo volta a se encontrar. Mike, o único que permaneceu em Derry, dá o sinal — uma nova onda de terror tomou a pequena cidade. É preciso unir forças novamente. Só eles têm a chave do enigma. Só eles sabem o que se esconde nas entranhas de Derry. Só eles podem vencer a Coisa."),
("Carrie", "Stephen King", "Suma", "Terror", "Carrie White é uma adolescente tímida, solitária e oprimida pela mãe, cristã ferrenha que vê pecado em tudo. A rotina na escola não alivia o dia a dia em casa. Para os colegas e professores, ela é estranha, não se encaixa e, por consequência, é alvo constante de bullying. O que ninguém sabe ainda é que, por trás da aparência frágil e indefesa, Carrie esconde um enorme poder: ela consegue mover objetos com a mente. Trancar portas. Derrubar velas. Dom ou maldição, isso mudará para sempre o destino das pessoas que algum dia lhe fizeram mal."),
("Salem", "Stephen King", "Suma", "Terror", "Ambientado na cidadezinha de Jerusalem`s Lot, na Nova Inglaterra, conta a história de três forasteiros. Ben Mears, um escritor que viveu alguns anos na cidade quando criança e está disposto a acertar contas com o próprio passado, Mark Petrie, um menino obcecado por monstros e filmes de terror e o Senhor Barlow, uma figura misteriosa que decide abrir uma loja na cidade. Após a chegada desses forasteiros, fatos inexplicáveis começam perturbar a rotina provinciana de Jerusalem`s Lot: uma criança é encontrada morta, habitantes começam a desaparecer sem deixar vestígios ou sucumbem a uma estranha doença. A morte passa a envolver a pequena cidade com seu toque maléfico e Ben e Mark são obrigados a escolher o único caminho que resta aos sobreviventes da praga: fugir. Mas isso não será tão simples: os destinos de Ben, Mark, Barlow e Jerusalem`s Lot estão agora para sempre interligados."),
("Psicose", "Robert Bloch", "Darkside", "Terror", "Psicose, o clássico de Robert Bloch, foi publicado originalmente em 1959, livremente inspirado no caso do assassino de Wisconsin, Ed Gein. O protagonista Norman Bates, assim como Gein, era um assassino solitário que vivia em uma localidade rural isolada, teve uma mãe dominadora, construiu um santuário para ela em um quarto e se vestia com roupas femininas.O livro teve dois lançamentos no Brasil, em 1959 e 1964. São, portanto, quase 50 anos sem uma edição no país, sem que a maioria das novas gerações pudesse ler a obra original que Hitchcock adaptou para o cinema em 1960. A DarkSide orgulhosamente tem o prazer de reparar este lapso, em julho de 2013, com o lançamento de Psicose em versões brochura (classic edition) e capa dura, limited edition que incluirá um caderno especial com imagens do clássico de Hitchcock.Uma história curiosa envolvendo o livro é que Alfred Hitchcock adquiriu anonimamente os direitos de Psycho e depois comprou todas as cópias do livro disponíveis no mercado para que ninguém o lesse e, consequentemente, ele conseguisse manter a surpresa do final da obra.Em Psicose, Bloch antecipou e prenunciou a explosão do fenômeno serial killer do final dos anos 1980 e começo dos 1990."),
("O Exorcista", "William Peter Blatty", "HarperCollins", "Terror", "Um clássico do terror com mais de 13 milhões de exemplares vendidos. Uma obra que mudou a cultura pop para sempre, O exorcista é o livro que deu origem ao maior filme de terror do século XX. Quatro décadas após chocar o mundo inteiro, a obra-prima de William Peter Blatty permanece uma metáfora moderna do combate entre o sagrado e o profano, em um dos romances mais macabros já escritos.. O mal assume várias formas. Seja com monstros, fantasmas ou demônios, tanto a literatura quanto o cinema sempre foram bem-sucedidos em representar a essência do nosso lado mais reprovável. O exorcista, no entanto, conseguiu superar qualquer outra obra do gênero. Inspirado no caso real do exorcismo de um adolescente, o escritor William Peter Blatty publicou em 1971 a perturbadora história de Chris MacNeil, uma atriz que sofre com inesperadas mudanças no comportamento da filha de 11 anos, Regan. Quando todos os esforços da ciência para descobrir o que há de errado com a menina falham e uma personalidade demoníaca parece vir à tona, Chris busca a ajuda da Igreja para tentar livrar a filha do que parece ser um raro caso de possessão. Cabe a Damien Karras, um padre da universidade de Georgetown, salvar a alma de Regan e ao mesmo tempo tentar restabelecer a própria fé, abalada desde a morte da mãe. Neste livro, Blatty conseguiu dar ao demônio a sua face mais revoltante: a corrupção de uma alma inocente. A menina Regan é, ao mesmo tempo, o mal e sua vítima. Ela recebe a pena e a revolta de leitores e espectadores em doses equivalentes e, mesmo quarenta anos depois, seu sofrimento e o abismo entre o que ela era e o que se torna continuam nos atormentando a cada página, a cada cena. Um clássico do terror que se mantém atual como somente os grandes nomes do gênero poderiam criar, O exorcista não se trata apenas de uma simples história sobre o bem contra o mal, ou sobre Deus contra o Demônio, mas também sobre a renovação da fé.."),
("O Bebê de Rosemary", "Ira Levin", "Darkside", "Terror", "Rosemary Woodhouse parece ter, finalmente, realizado todos os seus sonhos. Casada com um jovem ator por quem é apaixonada, logo muda-se para um apartamento aristocrático no imponente e prestigiado edifício Bramford. O prédio, célebre pela arquitetura vitoriana e pelos residentes famosos, é um cenário idílico para emoldurar o nascimento de uma grande paixão. Um início perfeito para uma jovem romântica, que planeja se dedicar à família e às alegrias do lar. Poucos meses após a mudança, Rosemary é agraciada pela semente divina da vida. A felicidade transborda de seu corpo e o fruto de seu ventre é aguardado com entusiasmo pelo marido e pelos novos vizinhos. No entanto, o sol brilha por pouco tempo, e o universo melancólico e assustador vai ganhando forma e sufocando, pouco a pouco, a jovem mãe, o bebê e os leitores."),
("A garota do lago", "Charlie Donlea", "Faro Editorial", "Thriller", "Summit Lake, uma pequena cidade entre montanhas, é esse tipo de lugar, bucólico e com encantadoras casas dispostas à beira de um longo trecho de água intocada.Duas semanas atrás, a estudante de direito Becca Eckersley foi brutalmente assassinada em uma dessas casas. Filha de um poderoso advogado, Becca estava no auge de sua vida. Atraída instintivamente pela notícia, a repórter Kelsey Castle vai até a cidade para investigar o caso. ...E LOGO SE ESTABELECE UMA CONEXÃO ÍNTIMA QUANDO UM VIVO CAMINHA NAS MESMAS PEGADAS DOS MORTOS...E enquanto descobre sobre as amizades de Becca, sua vida amorosa e os segredos que ela guardava, a repórter fica cada vez mais convencida de que a verdade sobre o que aconteceu com Becca pode ser a chave para superar as marcas sombrias de seu próprio passado."),
("Harry Potter e a Pedra Filosofal", " J.K. Rowling", "Pottermore Publishing", "Fantasia", "Quando virou o envelope, com a mão trêmula, Harry viu um lacre de cera púrpura com um brasão; um leão, uma águia, um texugo e uma cobra circulando uma grande letra H. Harry Potter nunca havia ouvido falar de Hogwarts quando as cartas começaram a aparecer no capacho da Rua dos Alfeneiros, nº 4. Escritos a tinta verde-esmeralda em pergaminho amarelado com um lacre de cera púrpura, as cartas eram rapidamente confiscadas por seus pavorosos tio e tia. Então, no aniversário de onze anos de Harry, um gigante com olhos que luziam como besouros negros chamado Rúbeo Hagrid surge com notícias surpreendentes: Harry Potter é um bruxo e tem uma vaga na Escola de Magia e Bruxaria de Hogwarts."),
("Harry Potter e o prisioneiro de Azkaban", " J.K. Rowling", "Pottermore Publishing", "Fantasia", "Bem-vindo ao ônibus Nôitibus Andante, o transporte de emergência para bruxos e bruxas perdidos. Basta esticar a mão da varinha, subir a bordo e podemos levá-lo aonde quiser. Quando o ônibus Nôitibus Andante surge repentinamente da escuridão e solta um guincho de seu freio bem à sua frente, mais um ano nada normal em Hogwarts começa para Harry Potter. Sirius Black, assassino em série fugitivo e seguidor do Lorde Voldemort, está à solta - e dizem que está indo atrás de Harry. Em sua primeira aula de Adivinhação, a professora Trelawney vê um agouro de morte nas folhas do chá de Harry... Mas talvez a parte mais assustadora seja os Dementadores patrulhando os pátios da escola, com seus beijos que sugam a alma..."),
("Harry Potter e o Cálice de Fogo", " J.K. Rowling", "Pottermore Publishing", "Fantasia", "Haverá três tarefas, espaçadas durante o ano letivo, que servirão para testar os campeões de diferentes maneiras... sua perícia em magia, sua coragem, seus poderes de dedução e, naturalmente, sua capacidade de enfrentar o perigo.' O Torneio Tribruxo será realizado em Hogwarts. Apenas bruxos acima dos dezessete anos de idade podem se inscrever - mas isso não impede que Harry sonhe em vencer a competição. E então, no Dia das Bruxas, quando o Cálice de Fogo faz sua seleção, Harry se surpreende ao ver que seu nome é um dos que a taça mágica escolhe. Ele terá de enfrentar tarefas mortais, dragões e bruxos das trevas, mas com a ajuda de seus melhores amigos, Ron e Hermione, talvez ele consiga sair dessa - vivo!"),
("Harry Potter e a Ordem da Fênix", " J.K. Rowling", "Pottermore Publishing", "Fantasia", "Você está compartilhando os pensamentos e emoções do Lorde das Trevas. O diretor acha que é desaconselhável que isto continue a acontecer. E quer que eu lhe ensine como fechar a mente ao Lorde das Trevas.' Tempos sombrios se abateram sobre Hogwarts. Depois do ataque dos Dementadores ao seu primo Dudley, Harry Potter sabe que Voldemort fará tudo para encontrá-lo. Muitos negam o retorno do Lorde das Trevas, mas Harry não está sozinho: uma ordem secreta se reúne no Largo Grimmauld para fazer frente às forças sombrias. Harry precisa permitir que o professor Snape o ensine a se proteger dos vorazes ataques de Voldemort à sua mente. Mas eles estão ficando cada vez mais fortes, e o tempo de Harry está acabando..."),
("Harry Potter e o enigma do Príncipe", " J.K. Rowling", "Pottermore Publishing", "Fantasia", "Lá estava, pairando no céu sobre a escola: o crânio verde flamejante com uma língua de cobra, a marca deixada pelos Comensais da Morte sempre que entravam em um prédio... sempre que matavam... Quando Dumbledore chega à Rua dos Alfeneiros numa certa noite de verão para buscar Harry Potter, a mão com que segura a varinha está enrugada e enegrecida, mas ele não revela o motivo. Segredos e suspeitas se espalham pelo Mundo Bruxo, e a própria Hogwarts não é mais segura. Harry está convencido de que Malfoy porta a Marca Negra: há um Comensal da Morte entre eles. Harry precisará de magia poderosa e amigos verdadeiros para explorar os segredos mais sombrios de Voldemort, e Dumbledore se prepara para encarar seu destino..."),
("Harry Potter e as Relíquias da Morte", " J.K. Rowling", "Pottermore Publishing", "Fantasia", "Entreguem-me Harry Potter, disse a voz de Voldemort, e ninguém sairá ferido. Entreguem-me Harry Potter, e não tocarei na escola. Entreguem-me Harry Potter, e serão recompensados. Ao subir no sidecar da moto de Hagrid e subir aos céus, deixando a Rua dos Alfeneiros pela última vez, Harry Potter sabe que o lorde Voldemort e os Comensais da Morte estão em seu encalço. O feitiço de proteção que manteve Harry seguro até o momento foi quebrado, mas ele não pode mais se esconder. O Lorde das Trevas está incutindo medo em tudo que Harry ama e, para detê-lo, Harry terá de encontrar e destruir as Horcruxes que restaram. A batalha final está para começar - Harry precisa enfrentar seu inimigo..."),
("O pequeno príncipe", "Antoine de Saint-Exupéry", "HarperCollins Brasil", "Fantasia", "O pequeno príncipe devolve a cada um o mistério da infância. De repente retornam os sonhos. Reaparece a lembrança de questionamentos, desvelam-se incoerências acomodadas, quase já imperceptíveis na pressa do dia a dia. Voltam ao coração escondidas recordações. O reencontro, o homem-menino."),
("A Guerra dos Tronos", "George R. R. Martin", "Suma", "Fantasia", "O verão pode durar décadas. O inverno, toda uma vida. E a guerra dos tronos começou. Como Guardião do Norte, lorde Eddard Stark não fica feliz quando o rei Robert o proclama a nova Mão do Rei. Sua honra o obriga a aceitar o cargo e deixar seu posto em Winterfell para rumar para a corte, onde os homens fazem o que lhes convém, não o que devem... e onde um inimigo morto é algo a ser admirado. Longe de casa e com a família dividida, Eddard se vê cada vez mais enredado nas intrigas mortais de Porto Real, sem saber que perigos ainda maiores espreitam a distância. Nas florestas ao norte de Winterfell, forças sobrenaturais se espalham por trás da Muralha que protege a região. E, nas Cidades Livres, o jovem Rei Dragão exilado na Rebelião de Robert planeja sua vingança e deseja recuperar sua herança de família: o Trono de Ferro de Westeros."),
("A fúria dos reis", "George R. R. Martin", "Suma", "Fantasia", "Um cometa da cor de fogo e sangue corta os céus. E, da antiga cidadela de Pedra do Dragão às costas áridas de Winterfell, reina o caos. Em A fúria dos reis, seis facções disputam o controle de uma terra dividida e o direito de ocupar o Trono de Ferro de Westeros – e estão dispostos a encarar tempestades, levantes e guerras para isso. Nesta história, irmão trama contra irmão e os mortos se levantam para caminhar pela noite. Aqui, uma princesa se disfarça de menino órfão, um cavaleiro se prepara para encarar uma pérfida feiticeira e bárbaros descem das Montanhas da Lua para saquear os campos. Em um contexto de incesto e fratricídio, alquimia e assassinato, a vitória será dos homens e mulheres que possuírem o mais frio aço... e o mais frio coração. Pois, quando se desperta a fúria dos reis, a terra inteira treme."),
("A tormenta de espadas", "George R. R. Martin", "Suma", "Fantasia", "O futuro de Westeros está em jogo, e ninguém descansará até que os Sete Reinos tenham explodido em uma verdadeira tormenta de espadas. Dos cinco pretendentes ao trono, um está morto e outro caiu em desgraça, e ainda assim a guerra continua em toda sua fúria, enquanto alianças são feitas e desfeitas. Joffrey, da Casa Lannister, ocupa o Trono de Ferro, como o instável governante dos Sete Reinos, ao passo que seu rival mais amargo, lorde Stannis, jaz derrotado e enfeitiçado pelas promessas da Mulher Vermelha. O jovem Robb, da Casa Stark, ainda comanda o Norte, contudo, e planeja sua batalha contra os Lannister, mesmo que sua irmã seja refém deles em Porto Real. Enquanto isso, Daenerys Targaryen atravessa um continente deixando um rastro de sangue a caminho de Westeros, levando consigo os três únicos dragões existentes em todo o mundo. Enquanto forças opostas avançam para uma gigantesca batalha final, um exército de selvagens chega dos confins da civilização. Em seu rastro vem uma horda de terríveis criaturas místicas – os Outros: um batalhão de mortos-vivos cujos corpos são imparáveis."),
("O Festim dos Corvos", "George R. R. Martin", "Suma", "Fantasia", "Há séculos os sete grandes reinos de Westeros se enfrentam em amargas disputas, batalhas e traições. Agora, com Joffrey Baratheon e Robb Stark fora da jogada e lordes insignificantes competindo pelas Ilhas de Ferro, a guerra que devorou o continente parece ter finalmente chegado ao fim. No entanto, como após todo grande conflito, não demora para que os sobreviventes, os bandidos, os renegados e os carniceiros avancem para disputar o espólio dos mortos. Por toda Westeros os lordes se agitam, formando alianças e fazendo planos, enquanto nomes conhecidos e desconhecidos se apresentam para tomar parte das danças políticas. Todos precisam lançar mão de suas habilidades e poderes para encarar os tempos de terror que se aproximam. Nobres e plebeus, soldados e feiticeiros, assassinos e saqueadores devem arriscar suas fortunas... e suas vidas, pois em um festim de corvos, muitos são os convidados ― e poucos os sobreviventes."),
("A dança dos dragões", "George R. R. Martin", "Suma", "Fantasia", "É outono em Westeros, e a Guerra dos Cinco Reis parece finalmente entrar na reta final. Stannis Baratheon se instala no Norte e jura conquistar o apoio dos senhores da região para continuar sua luta pelo trono, embora seja atrapalhado pela invasão de homens de ferro em grande parte da costa. Na Muralha, Jon Snow é eleito o 998º Senhor Comandante da Patrulha da Noite, mas inimigos o cercam de todos os lados, tanto na Patrulha quanto para além da Muralha. Enquanto isso, Tyrion Lannister atravessa o Mar Estreito rumo a Pentos, sem objetivos definidos, sem aliados e cada vez mais sem opções. Na Baía dos Escravos, Daenerys Targaryen conquista a cidade de Meereen e decide ficar e governá-la, praticando as habilidades de liderança que serão tão necessárias quando partir para Westeros. No entanto, sua presença já foi notada por muitos senhores nos Sete Reinos, e das Ilhas de Ferro e de Dorne, de Vilavelha e das Cidades Livres, emissários estão a caminho, querendo se unir à sua causa e, se possível, usá-la para os próprios fins. Em todos os cantos conflitos ganham vida e traições vêm daqueles mais próximos. Guerreiros, selvagens, nobres e escravos – todos têm pela frente um longo inverno, enquanto destino, ambição e política ditam o ritmo da dança mais perigosa de todas."),
("Deuses Americanos", "Neil Gaiman", "Intrínseca", "Fantasia", "A saga de Deuses americanos é contada ao longo da jornada de Shadow Moon, um ex-presidiário de trinta e poucos anos que acabou de ser libertado e cujo único objetivo é voltar para casa e para a esposa, Laura. Os planos de Shadow se transformam em poeira quando ele descobre que Laura morreu em um acidente de carro. Sem lar, sem emprego e sem rumo, ele conhece Wednesday, um homem de olhar enigmático que está sempre com um sorriso no rosto, embora pareça nunca achar graça de nada. Depois de apostas, brigas e um pouco de hidromel, Shadow aceita trabalhar para Wednesday e embarca em uma viagem tumultuada e reveladora por cidades inusitadas dos Estados Unidos, um país tão estranho para Shadow quanto para Gaiman. É nesses encontros e desencontros que o protagonista se depara com os deuses ― os antigos (que chegaram ao Novo Mundo junto dos imigrantes) e os modernos (o dinheiro, a televisão, a tecnologia, as drogas) ―, que estão se preparando para uma guerra que ninguém viu, mas que já começou. O motivo? O poder de não ser esquecido."),
("As Crônicas de Nárnia", "C. S. Lewis", "WMF Martins Fontes", "Fantasia", "Viagens ao fim do mundo, criaturas fantásticas e batalhas épicas entre o bem e o mal - o que mais um leitor poderia querer de um livro? O livro que tem tudo isso é 'O leão, a feiticeira e o guarda-roupa', escrito em 1949 por Clive Staples Lewis. MasLewis não parou por aí. Seis outros livros vieram depois e, juntos, ficaram conhecidos como 'As crônicas de Nárnia'. Nos últimos cinqüenta anos, 'As crônicas de Nárnia' transcenderam o gênero da fantasia para se tornar parte do cânone da literaturaclássica. Cada um dos sete livros é uma obra-prima, atraindo o leitor para um mundo em que a magia encontra a realidade, e o resultado é um mundo ficcional que tem fascinado gerações. Esta edição apresenta todas as sete crônicas integralmente, num único volume. Os livros são apresentados de acordo com a ordem de preferência de Lewis, cada capítulo com uma ilustração do artista original, Pauline Baynes. Enganosamente simples e direta, 'As crônicas de Nárnia' continuam cativando os leitores com aventuras, personagens e fatos que falam a pessoas de todas as idades."),
("O Hobbit", " J.R.R. Tolkien", "HarperCollins", "Fantasia", "Bilbo Bolseiro era um dos mais respeitáveis hobbits de todo o Condado até que, um dia, o mago Gandalf bate à sua porta. A partir de então, toda sua vida pacata e campestre soprando anéis de fumaça com seu belo cachimbo começa a mudar. Ele é convocado a participar de uma aventura por ninguém menos do que Thorin Escudo-de-Carvalho, um príncipe do poderoso povo dos Anãos. Esta jornada fará Bilbo, Gandalf e 13 anãos atravessarem a Terra-média, passando por inúmeros perigos, como os imensos trols, as Montanhas Nevoentas infestadas de gobelins ou a muito antiga e misteriosa Trevamata, até chegarem (se conseguirem) na Montanha Solitária. Lá está um incalculável tesouro, mas há um porém. Deitado em cima dele está Smaug, o Dourado, um dragão malicioso que... bem, você terá que ler para descobrir. Lançado em 1937, O Hobbit é um divisor de águas na literatura de fantasia mundial. Mais de 80 anos após a sua publicação, o livro que antecede os ocorridos em O Senhor dos Anéis continua arrebatando fãs de todas as idades, talvez pelo seu tom brincalhão com uma pitada de magia élfica, ou talvez porque J.R.R. Tolkien tenha escrito o melhor livro infantojuvenil de todos os tempos."),
("O Hobbit", " J.R.R. Tolkien", "HarperCollins", "Aventura", "Bilbo Bolseiro era um dos mais respeitáveis hobbits de todo o Condado até que, um dia, o mago Gandalf bate à sua porta. A partir de então, toda sua vida pacata e campestre soprando anéis de fumaça com seu belo cachimbo começa a mudar. Ele é convocado a participar de uma aventura por ninguém menos do que Thorin Escudo-de-Carvalho, um príncipe do poderoso povo dos Anãos. Esta jornada fará Bilbo, Gandalf e 13 anãos atravessarem a Terra-média, passando por inúmeros perigos, como os imensos trols, as Montanhas Nevoentas infestadas de gobelins ou a muito antiga e misteriosa Trevamata, até chegarem (se conseguirem) na Montanha Solitária. Lá está um incalculável tesouro, mas há um porém. Deitado em cima dele está Smaug, o Dourado, um dragão malicioso que... bem, você terá que ler para descobrir. Lançado em 1937, O Hobbit é um divisor de águas na literatura de fantasia mundial. Mais de 80 anos após a sua publicação, o livro que antecede os ocorridos em O Senhor dos Anéis continua arrebatando fãs de todas as idades, talvez pelo seu tom brincalhão com uma pitada de magia élfica, ou talvez porque J.R.R. Tolkien tenha escrito o melhor livro infantojuvenil de todos os tempos."),
("O Silmarillion", " J.R.R. Tolkien", "HarperCollins", "Fantasia", "O Silmarillion é o relato dos Dias Antigos da Primeira Era do mundo criado por J.R.R. Tolkien. É a história longínqua para a qual os personagens de O Senhor dos Anéis e O Hobbit olham para trás, e em cujos eventos alguns deles, como Elrond e Galadriel, tomaram parte. Os contos de O Silmarillion se passam na época em que Morgoth, o Primeiro Senhor Sombrio, habitava a Terra-média, e os Altos-Elfos guerreavam contra ele pela recuperação das Silmarils, as joias que continham a pura luz de Valinor. O livro começa com o Ainulindalë, o mito da criação do Universo, seguido pelo Valaquenta, onde estão descritas a natureza e os poderes de cada um dos deuses. Em o “Quenta Silmarillion” há o início da contagem dos dias em Arda (o mundo onde está inserido o continente da Terra-média), a história dos Elfos na Terra Abençoada do Oeste, seus êxodos e o desenrolar das guerras élficas em Beleriand, que culminaram com o final da Primeira Era. O Akallabêth narra o apogeu e a queda do reino da grande ilha de Númenor no final da Segunda Era. Por fim, Dos Anéis de Poder fala dos grandes eventos no final da Terceira Era, como narrado em O Senhor dos Anéis."),
("O Senhor dos Anéis", " J.R.R. Tolkien", "HarperCollins", "Fantasia", "O segundo volume de O Senhor dos Anéis, mais importante épico de fantasia moderno, narra os caminhos separados seguidos pelos membros da Sociedade do Anel em sua luta para deter Sauron, o Senhor Sombrio da terra de Mordor, e destruir o Um Anel, no qual está contida a maior parte do poder do tirano demoníaco imaginado por J.R.R. Tolkien. Um ataque-surpresa pôs fim à jornada conjunta da Sociedade do Anel. De um lado, o trio formado pelo elfo Legolas, pelo anão Gimli e por Aragorn, herdeiro da realeza dos Homens, tenta resgatar os jovens hobbits Merry e Pippin, capturados por guerreiros-órquicos. A busca pelos companheiros perdidos levará os três a confrontar os cavaleiros do reino de Rohan e o mago renegado Saruman, que também deseja o Um Anel para si. Enquanto isso, do outro lado das montanhas, Frodo e Sam buscam uma maneira de entrar em Mordor e chegar até a montanha onde o Anel foi forjado, único lugar onde é possível destruí-lo. Para isso, acabam recebendo a ajuda de seu mais improvável aliado: Gollum, a criatura que chegou a ter o Anel sob seu poder durante centenas de anos e que ainda é devorada, em corpo e alma, pelo desejo de voltar a possuí-lo."),
("O Senhor dos Anéis: As duas torres", " J.R.R. Tolkien", "HarperCollins", "Fantasia", "O segundo volume de O Senhor dos Anéis, mais importante épico de fantasia moderno, narra os caminhos separados seguidos pelos membros da Sociedade do Anel em sua luta para deter Sauron, o Senhor Sombrio da terra de Mordor, e destruir o Um Anel, no qual está contida a maior parte do poder do tirano demoníaco imaginado por J.R.R. Tolkien. Um ataque-surpresa pôs fim à jornada conjunta da Sociedade do Anel. De um lado, o trio formado pelo elfo Legolas, pelo anão Gimli e por Aragorn, herdeiro da realeza dos Homens, tenta resgatar os jovens hobbits Merry e Pippin, capturados por guerreiros-órquicos. A busca pelos companheiros perdidos levará os três a confrontar os cavaleiros do reino de Rohan e o mago renegado Saruman, que também deseja o Um Anel para si. Enquanto isso, do outro lado das montanhas, Frodo e Sam buscam uma maneira de entrar em Mordor e chegar até a montanha onde o Anel foi forjado, único lugar onde é possível destruí-lo. Para isso, acabam recebendo a ajuda de seu mais improvável aliado: Gollum, a criatura que chegou a ter o Anel sob seu poder durante centenas de anos e que ainda é devorada, em corpo e alma, pelo desejo de voltar a possuí-lo."),
("O Senhor dos Anéis: A Sociedade do Anel", " J.R.R. Tolkien", "HarperCollins", "Fantasia", "O volume inicial de O Senhor dos Anéis, lançado originalmente em julho de 1954, foi o primeiro grande épico de fantasia moderno, conquistando milhões de leitores e se tornando o padrão de referência para todas as outras obras do gênero até hoje. A imaginação prodigiosa de J.R.R. Tolkien e seu conhecimento profundo das antigas mitologias da Europa permitiram que ele criasse um universo tão complexo e convincente quanto o mundo real. A Sociedade do Anel começa no Condado, a região rural do oeste da Terra-média onde vivem os diminutos e pacatos hobbits. Bilbo Bolseiro, um dos raros aventureiros desse povo, cujas peripécias foram contadas em O Hobbit, resolve ir embora do Condado e deixa sua considerável herança nas mãos de seu jovem parente Frodo. O mais importante legado de Bilbo é o anel mágico que costumava usar para se tornar invisível. No entanto, o mago Gandalf, companheiro de aventuras do velho hobbit, revela a Frodo que o objeto é o Um Anel, a raiz do poder demoníaco de Sauron, o Senhor Sombrio, que deseja escravizar todos os povos da Terra-média. A única maneira de eliminar a ameaça de Sauron é destruir o Um Anel nas entranhas da própria montanha de fogo onde foi forjado. A revelação faz com que Frodo e seus companheiros hobbits Sam, Merry e Pippin deixem a segurança do Condado e iniciem uma perigosa jornada rumo ao leste. Ao lado de representantes dos outros Povos Livres que resistem ao Senhor Sombrio, eles formam a Sociedade do Anel."),
("O Senhor dos Anéis: O Retorno do rei", " J.R.R. Tolkien", "HarperCollins", "Fantasia", "A sombra dos exércitos do Senhor do Escuro cresce cada vez mais. Homens, anões e elfos unem-se para lutar contra a Escuridão. Enquanto isso, Frodo e Sam penetram na terra de Mordor, em sua empreitada heroica para destruir o Anel. O Retorno do Rei é a terceira parte da grande obra de ficção fantástica de J. R. R. Tolkien, O Senhor dos Anéis. É impossível transmitir ao novo leitor todas as qualidades e o alcance do livro. Alternadamente cômica, singela, épica, monstruosa e diabólica, a narrativa desenvolve-se em meio a inúmeras mudanças de cenários e de personagens, num mundo imaginário absolutamente convincente em seus detalhes. Nas palavras do romancista Richard Hughes, “quanto à amplitude imaginativa, a obra praticamente não tem paralelos e é quase igualmente notável na sua vividez e na habilidade narrativa, que mantêm o leitor preso página após página”. Tolkien criou em O Senhor dos Anéis uma nova mitologia num mundo inventado que demonstrou possuir um poder de atração atemporal."),
("O Silmarillion", " J.R.R. Tolkien", "HarperCollins", "Aventura", "O Silmarillion é o relato dos Dias Antigos da Primeira Era do mundo criado por J.R.R. Tolkien. É a história longínqua para a qual os personagens de O Senhor dos Anéis e O Hobbit olham para trás, e em cujos eventos alguns deles, como Elrond e Galadriel, tomaram parte. Os contos de O Silmarillion se passam na época em que Morgoth, o Primeiro Senhor Sombrio, habitava a Terra-média, e os Altos-Elfos guerreavam contra ele pela recuperação das Silmarils, as joias que continham a pura luz de Valinor. O livro começa com o Ainulindalë, o mito da criação do Universo, seguido pelo Valaquenta, onde estão descritas a natureza e os poderes de cada um dos deuses. Em o “Quenta Silmarillion” há o início da contagem dos dias em Arda (o mundo onde está inserido o continente da Terra-média), a história dos Elfos na Terra Abençoada do Oeste, seus êxodos e o desenrolar das guerras élficas em Beleriand, que culminaram com o final da Primeira Era. O Akallabêth narra o apogeu e a queda do reino da grande ilha de Númenor no final da Segunda Era. Por fim, Dos Anéis de Poder fala dos grandes eventos no final da Terceira Era, como narrado em O Senhor dos Anéis."),
("O Senhor dos Anéis", " J.R.R. Tolkien", "HarperCollins", "Aventura", "O segundo volume de O Senhor dos Anéis, mais importante épico de fantasia moderno, narra os caminhos separados seguidos pelos membros da Sociedade do Anel em sua luta para deter Sauron, o Senhor Sombrio da terra de Mordor, e destruir o Um Anel, no qual está contida a maior parte do poder do tirano demoníaco imaginado por J.R.R. Tolkien. Um ataque-surpresa pôs fim à jornada conjunta da Sociedade do Anel. De um lado, o trio formado pelo elfo Legolas, pelo anão Gimli e por Aragorn, herdeiro da realeza dos Homens, tenta resgatar os jovens hobbits Merry e Pippin, capturados por guerreiros-órquicos. A busca pelos companheiros perdidos levará os três a confrontar os cavaleiros do reino de Rohan e o mago renegado Saruman, que também deseja o Um Anel para si. Enquanto isso, do outro lado das montanhas, Frodo e Sam buscam uma maneira de entrar em Mordor e chegar até a montanha onde o Anel foi forjado, único lugar onde é possível destruí-lo. Para isso, acabam recebendo a ajuda de seu mais improvável aliado: Gollum, a criatura que chegou a ter o Anel sob seu poder durante centenas de anos e que ainda é devorada, em corpo e alma, pelo desejo de voltar a possuí-lo."),
("O Senhor dos Anéis: As duas torres", " J.R.R. Tolkien", "HarperCollins", "Aventura", "O segundo volume de O Senhor dos Anéis, mais importante épico de fantasia moderno, narra os caminhos separados seguidos pelos membros da Sociedade do Anel em sua luta para deter Sauron, o Senhor Sombrio da terra de Mordor, e destruir o Um Anel, no qual está contida a maior parte do poder do tirano demoníaco imaginado por J.R.R. Tolkien. Um ataque-surpresa pôs fim à jornada conjunta da Sociedade do Anel. De um lado, o trio formado pelo elfo Legolas, pelo anão Gimli e por Aragorn, herdeiro da realeza dos Homens, tenta resgatar os jovens hobbits Merry e Pippin, capturados por guerreiros-órquicos. A busca pelos companheiros perdidos levará os três a confrontar os cavaleiros do reino de Rohan e o mago renegado Saruman, que também deseja o Um Anel para si. Enquanto isso, do outro lado das montanhas, Frodo e Sam buscam uma maneira de entrar em Mordor e chegar até a montanha onde o Anel foi forjado, único lugar onde é possível destruí-lo. Para isso, acabam recebendo a ajuda de seu mais improvável aliado: Gollum, a criatura que chegou a ter o Anel sob seu poder durante centenas de anos e que ainda é devorada, em corpo e alma, pelo desejo de voltar a possuí-lo."),
("O Senhor dos Anéis: A Sociedade do Anel", " J.R.R. Tolkien", "HarperCollins", "Aventura", "O volume inicial de O Senhor dos Anéis, lançado originalmente em julho de 1954, foi o primeiro grande épico de fantasia moderno, conquistando milhões de leitores e se tornando o padrão de referência para todas as outras obras do gênero até hoje. A imaginação prodigiosa de J.R.R. Tolkien e seu conhecimento profundo das antigas mitologias da Europa permitiram que ele criasse um universo tão complexo e convincente quanto o mundo real. A Sociedade do Anel começa no Condado, a região rural do oeste da Terra-média onde vivem os diminutos e pacatos hobbits. Bilbo Bolseiro, um dos raros aventureiros desse povo, cujas peripécias foram contadas em O Hobbit, resolve ir embora do Condado e deixa sua considerável herança nas mãos de seu jovem parente Frodo. O mais importante legado de Bilbo é o anel mágico que costumava usar para se tornar invisível. No entanto, o mago Gandalf, companheiro de aventuras do velho hobbit, revela a Frodo que o objeto é o Um Anel, a raiz do poder demoníaco de Sauron, o Senhor Sombrio, que deseja escravizar todos os povos da Terra-média. A única maneira de eliminar a ameaça de Sauron é destruir o Um Anel nas entranhas da própria montanha de fogo onde foi forjado. A revelação faz com que Frodo e seus companheiros hobbits Sam, Merry e Pippin deixem a segurança do Condado e iniciem uma perigosa jornada rumo ao leste. Ao lado de representantes dos outros Povos Livres que resistem ao Senhor Sombrio, eles formam a Sociedade do Anel."),
("O Senhor dos Anéis: O Retorno do rei", " J.R.R. Tolkien", "HarperCollins", "Aventura", "A sombra dos exércitos do Senhor do Escuro cresce cada vez mais. Homens, anões e elfos unem-se para lutar contra a Escuridão. Enquanto isso, Frodo e Sam penetram na terra de Mordor, em sua empreitada heroica para destruir o Anel. O Retorno do Rei é a terceira parte da grande obra de ficção fantástica de J. R. R. Tolkien, O Senhor dos Anéis. É impossível transmitir ao novo leitor todas as qualidades e o alcance do livro. Alternadamente cômica, singela, épica, monstruosa e diabólica, a narrativa desenvolve-se em meio a inúmeras mudanças de cenários e de personagens, num mundo imaginário absolutamente convincente em seus detalhes. Nas palavras do romancista Richard Hughes, “quanto à amplitude imaginativa, a obra praticamente não tem paralelos e é quase igualmente notável na sua vividez e na habilidade narrativa, que mantêm o leitor preso página após página”. Tolkien criou em O Senhor dos Anéis uma nova mitologia num mundo inventado que demonstrou possuir um poder de atração atemporal."),
("Harry Potter e a Pedra Filosofal", " J.K. Rowling", "Pottermore Publishing", "Aventura", "Quando virou o envelope, com a mão trêmula, Harry viu um lacre de cera púrpura com um brasão; um leão, uma águia, um texugo e uma cobra circulando uma grande letra H. Harry Potter nunca havia ouvido falar de Hogwarts quando as cartas começaram a aparecer no capacho da Rua dos Alfeneiros, nº 4. Escritos a tinta verde-esmeralda em pergaminho amarelado com um lacre de cera púrpura, as cartas eram rapidamente confiscadas por seus pavorosos tio e tia. Então, no aniversário de onze anos de Harry, um gigante com olhos que luziam como besouros negros chamado Rúbeo Hagrid surge com notícias surpreendentes: Harry Potter é um bruxo e tem uma vaga na Escola de Magia e Bruxaria de Hogwarts."),
("Harry Potter e o prisioneiro de Azkaban", " J.K. Rowling", "Pottermore Publishing", "Aventura", "Bem-vindo ao ônibus Nôitibus Andante, o transporte de emergência para bruxos e bruxas perdidos. Basta esticar a mão da varinha, subir a bordo e podemos levá-lo aonde quiser. Quando o ônibus Nôitibus Andante surge repentinamente da escuridão e solta um guincho de seu freio bem à sua frente, mais um ano nada normal em Hogwarts começa para Harry Potter. Sirius Black, assassino em série fugitivo e seguidor do Lorde Voldemort, está à solta - e dizem que está indo atrás de Harry. Em sua primeira aula de Adivinhação, a professora Trelawney vê um agouro de morte nas folhas do chá de Harry... Mas talvez a parte mais assustadora seja os Dementadores patrulhando os pátios da escola, com seus beijos que sugam a alma..."),
("Harry Potter e o Cálice de Fogo", " J.K. Rowling", "Pottermore Publishing", "Aventura", "Haverá três tarefas, espaçadas durante o ano letivo, que servirão para testar os campeões de diferentes maneiras... sua perícia em magia, sua coragem, seus poderes de dedução e, naturalmente, sua capacidade de enfrentar o perigo.' O Torneio Tribruxo será realizado em Hogwarts. Apenas bruxos acima dos dezessete anos de idade podem se inscrever - mas isso não impede que Harry sonhe em vencer a competição. E então, no Dia das Bruxas, quando o Cálice de Fogo faz sua seleção, Harry se surpreende ao ver que seu nome é um dos que a taça mágica escolhe. Ele terá de enfrentar tarefas mortais, dragões e bruxos das trevas, mas com a ajuda de seus melhores amigos, Ron e Hermione, talvez ele consiga sair dessa - vivo!"),
("Harry Potter e a Ordem da Fênix", " J.K. Rowling", "Pottermore Publishing", "Aventura", "Você está compartilhando os pensamentos e emoções do Lorde das Trevas. O diretor acha que é desaconselhável que isto continue a acontecer. E quer que eu lhe ensine como fechar a mente ao Lorde das Trevas.' Tempos sombrios se abateram sobre Hogwarts. Depois do ataque dos Dementadores ao seu primo Dudley, Harry Potter sabe que Voldemort fará tudo para encontrá-lo. Muitos negam o retorno do Lorde das Trevas, mas Harry não está sozinho: uma ordem secreta se reúne no Largo Grimmauld para fazer frente às forças sombrias. Harry precisa permitir que o professor Snape o ensine a se proteger dos vorazes ataques de Voldemort à sua mente. Mas eles estão ficando cada vez mais fortes, e o tempo de Harry está acabando..."),
("Harry Potter e o enigma do Príncipe", " J.K. Rowling", "Pottermore Publishing", "Aventura", "Lá estava, pairando no céu sobre a escola: o crânio verde flamejante com uma língua de cobra, a marca deixada pelos Comensais da Morte sempre que entravam em um prédio... sempre que matavam... Quando Dumbledore chega à Rua dos Alfeneiros numa certa noite de verão para buscar Harry Potter, a mão com que segura a varinha está enrugada e enegrecida, mas ele não revela o motivo. Segredos e suspeitas se espalham pelo Mundo Bruxo, e a própria Hogwarts não é mais segura. Harry está convencido de que Malfoy porta a Marca Negra: há um Comensal da Morte entre eles. Harry precisará de magia poderosa e amigos verdadeiros para explorar os segredos mais sombrios de Voldemort, e Dumbledore se prepara para encarar seu destino..."),
("Harry Potter e as Relíquias da Morte", " J.K. Rowling", "Pottermore Publishing", "Aventura", "Entreguem-me Harry Potter, disse a voz de Voldemort, e ninguém sairá ferido. Entreguem-me Harry Potter, e não tocarei na escola. Entreguem-me Harry Potter, e serão recompensados. Ao subir no sidecar da moto de Hagrid e subir aos céus, deixando a Rua dos Alfeneiros pela última vez, Harry Potter sabe que o lorde Voldemort e os Comensais da Morte estão em seu encalço. O feitiço de proteção que manteve Harry seguro até o momento foi quebrado, mas ele não pode mais se esconder. O Lorde das Trevas está incutindo medo em tudo que Harry ama e, para detê-lo, Harry terá de encontrar e destruir as Horcruxes que restaram. A batalha final está para começar - Harry precisa enfrentar seu inimigo..."),
("Verity", "Colleen Hoover", "Galera", "Thriller", "Verity Crawford é a autora best-seller por trás de uma série de sucesso. Ela está no auge de sua carreira, aclamada pela crítica e pelo público, no entanto, um súbito e terrível acidente acaba interrompendo suas atividades, deixando-a sem condições de concluir a história... E é nessa complexa circunstância que surge Lowen Ashleigh, uma escritora à beira da falência convidada a escrever, sob um pseudônimo, os três livros restantes da já consolidada série. Para que consiga entender melhor o processo criativo de Verity com relação aos livros publicados e, ainda, tentar descobrir seus possíveis planos para os próximos, Lowen decide passar alguns dias na casa dos Crawford, imersa no caótico escritório de Verity - e, lá, encontra uma espécie de autobiografia onde a escritora narra os fatos acontecidos desde o dia em que conhece Jeremy, seu marido, até os instantes imediatamente anteriores a seu acidente - incluindo sua perspectiva sobre as tragédias ocorridas às filhas do casal. Quanto mais o tempo passa, mais Lowen se percebe envolvida em uma confusa rede de mentiras e segredos, e, lentamente, adquire sua própria posição no jogo psicológico que rodeia aquela casa. Emocional e fisicamente atraída por Jeremy, ela precisa decidir: expor uma versão que nem ele conhece sobre a própria esposa ou manter o sigilo dos escritos de Verity?"),
("É Assim que Acaba", "Colleen Hoover", "Galera", "Romance", "Em É assim que acaba, Colleen Hoover nos apresenta Lily, uma jovem que se mudou de uma cidadezinha do Maine para Boston, se formou em marketing e abriu a própria floricultura. E é em um dos terraços de Boston que ela conhece Ryle, um neurocirurgião confiante, teimoso e talvez até um pouco arrogante, com uma grande aversão a relacionamentos, mas que se sente muito atraído por ela. Quando os dois se apaixonam, Lily se vê no meio de um relacionamento turbulento que não é o que ela esperava. Mas será que ela conseguirá enxergar isso, por mais doloroso que seja? É assim que acaba é uma narrativa poderosa sobre a força necessária para fazer as escolhas certas nas situações mais difíceis. Considerada a obra mais pessoal de Hoover, o livro aborda sem medo alguns tabus da sociedade para explorar a complexidade das relações tóxicas, e como o amor e o abuso muitas vezes coexistem em uma confusão de sentimentos."),
("É assim que começa", "Colleen Hoover", "Galera", "Romance", "Lily Bloom continua administrando uma floricultura. Seu ex-marido abusivo, Ryle Kincaid, ainda é um cirurgião. Mas agora os dois estão oficialmente divorciados e dividem a guarda da filha, Emerson. Quando Lily esbarra em Atlas ― com quem não fala há quase dois anos ―, parece que finalmente chegou o momento de retomar o relacionamento da adolescência, já que ele também está solteiro e parece retribuir os sentimentos de Lily. Mas apesar de divorciada, Lily não está exatamente livre de Ryle. Culpando Atlas pelo fim de seu casamento, Ryle não está nada disposto a aceitar o novo relacionamento de Lily, ainda mais com Atlas, o último homem que aceitaria ver perto de sua filha e da ex-esposa. Alternando entre os pontos de vista de Atlas e Lily, É assim que começa retoma logo após o epílogo de É assim que acaba. Revelando mais sobre o passado de Atlas e acompanhando a jornada de Lily para abraçar a sua segunda chance, no amor enquanto lida com um ex-marido ciumento, É assim que começa prova que ninguém entrega uma leitura mais emocionante do que Colleen Hoover.");



INSERT INTO livros 
(titulo, autor, editora, genero, sinopse)

VALUES

("Auto da Compadecida", "Ariano Suassuna", "Nova Fronteira", "Comédia", "As aventuras de João Grilo e Chicó, dois nordestinos pobres que vivem de golpes para sobreviver. Eles estão sempre enganando o povo de um pequeno vilarejo, inclusive o temido cangaceiro Severino de Aracaju, que os persegue pela região.."),
("Melancia", "Marian Keyes", "Bertrand Brasil", "Comédia", "Com este romance engraçadíssimo e irreverente, a autora irlandesa Marian Keyes conquistou milhares de leitores no Brasil e no mundo. Melancia é sobre sobrevivência e a arte de manter o bom humor mesmo diante das circunstâncias mais adversas. Com 29 anos, uma filha recém-nascida e um marido que acabou de confessar um caso com a vizinha, Claire Walsh se resume a um coração partido e um corpo inteiramente redondo, aparentando uma melancia. Não tendo nada melhor em vista, ela volta a morar com sua excêntrica família. Depois de muitos dias em depressão, Claire decide avaliar os prós e contras do casamento, e começa a se sentir bem melhor. É justamente nesse momento que James, seu ex-marido, reaparece. Claire irá recebê-lo, mas lhe reservará uma bela surpresa."),
("Los Angeles", "Marian Keyes", "Bertrand Brasil", "Comédia", "Será que em meio a tanta aventura, drama e comédia pastelão haverá espaço para um romance? Maggie sempre foi uma anjinha, a cria mais certinha da complicada família Walsh... até se cansar de andar na linha e de todas as regras que a prendiam a um dia-a-dia em preto e branco. Maggie, então, decide se mandar para o lugar onde a realidade promete ser em Technicolor: Hollywood, claro! Terra do glamour, da liberdade, da beleza, da luxúria e, obviamente, da diversão! Em Los Angeles, acompanhamos Maggie Walsh em sua busca por um sentido na vida em meio às vários martínis, algumas decepções e muitas risadas."),
("Chá de sumiço", "Marian Keyes", "Bertrand Brasil", "Comédia", "Helen Walsh não vive um bom momento. O trabalho como detetive particular não vai bem, o apartamento foi tomado por falta de pagamento e um ex-namorado surge com uma proposta de trabalho: encontrar o desaparecido músico da Laddz, a boy band do momento. Precisando do dinheiro, ela se vê forçada a aceitar, o que causa uma confusão em sua cabeça ao conviver com o ex e precisar acalmar o atual namorado. Ao tentar seguir suas próprias regras, Helen será arrastada para o mundo complexo, perigoso e glamoroso do showbiz, percebendo que seu pior inimigo ainda está por surgir. Irresistível, comovente e muito engraçado, Chá de sumiço é diferente de todos os romances do gênero, e a protagonista – corajosa, vulnerável e dona de uma língua afiadíssima – é a heroína perfeita para os novos tempos."),
("Sushi", "Marian Keyes", "Bertrand Brasil", "Comédia", "Perspicaz, engraçado e humano, este romance de Marian Keyes consolida sua posição como a mais popular jovem autora da Grã-Bretanha. A editora de revistas Lisa Edwards acha que sua vida acabou quando descobre que terá que se mudar para a Irlanda, com a missão de lançar a revista Garota. Ashling Kennedy, a editora assistente da Garota, é a Rainha da Ansiedade, sempre achou que falta algo mais em sua vida e morre de inveja de sua amiga, Clodagh. Conhecida como Princesa, Clodagh sempre teve a vida dos sonhos, e hoje vive seu conto de fadas ao lado do marido e dos filhos. Mas então, por que será anda sentindo vontade de beijar  um sapo? Sushi é um livro sobre a busca da felicidade. E ensina que, quando você deixa as coisas ferverem sob a superfície por tempo demais, elas acabam transbordando."),
("Serviço de Atendimento aos Corações Partidos", "Giulia Paim", "Melhoramentos", "Comédia", "Uma plataforma de streaming, uma garota desiludida, um atendente de SAC, um chefe mau-carater, uma drag queen, um pug desaparecido e uma disputa de sinuca se encontram nesta aventura envolvente no Rio de Janeiro.Em pleno Dia dos Namorados, Tina recebe a notícia que mais temia: sua irmã, Alessandra, acaba de ficar noiva de Bruno, o rapaz por quem Tina nutre uma paixão platônica. Arrasada com a novidade, a garota decide afogar suas mágoas em um pacote extragrande de salgadinho enquanto assiste a um filme no NettyMe. Isso se a plataforma estivesse funcionando...Após mandar uma foto, digamos, comprometedora para a garota com quem está saindo há alguns meses e descobrir que eles não são exclusivos, Tiago é convocado por seu mal-encarado chefe para trabalhar no sábado, bem no Dia dos Namorados. Desiludido com sua vida amorosa, Tiago atende a ligação de uma garota que está tendo problemas para acessar sua conta no NettyMe. O que ele não poderia imaginar é que essa ligação mudaria sua vida para sempre, e de várias maneiras!"),
("Clube do Livro dos Homens", "Lyssa Kay Adams", "Arqueiro", "Comédia", "Gavin Scott é um astro do beisebol, devotado ao esporte. No auge de sua carreira, ele descobre um segredo humilhante: a esposa, Thea, sempre fingiu ter prazer na cama. Magoado, Gavin para de falar com ela e acaba piorando o relacionamento, que já vinha se deteriorando. Quando Thea pede o divórcio, ele percebe que o orgulho e o medo podem fazê-lo perder tudo. Bem-vindos ao Clube do Livro dos Homens Desesperado, Gavin encontra ajuda onde menos espera: um clube secreto de romances, composto por alguns dos seus colegas de time. Para salvar seu casamento, eles recorrem à leitura de uma sensual trama de época, Cortejando a condessa. Só que vai ser preciso muito mais do que palavras floreadas e gestos grandiosos para que Gavin recupere a confiança da esposa."),
("Cadê Você Bernadette?", "Maria Sample", "Companhia das Letras", "Comédia", "Essa é uma divertida história de mãe e filha! Bee passa o livro tentando descobrir quem é de fato sua mãe Bernadette Fox e onde ela está, já a personagem desaparece do mapa após se ver obrigada a fazer uma viagem em família para a Antártida. Esse é o segundo livro da norte-americana Maria Samples. Não espere sentimentalismo barato dela, ok?"),
("Holy Cow: Uma Fábula Animal", "David Duchovny", "Record", "Comédia", "Lembra do Fox Mulder, da série “Arquivo X”? Pois seu intérprete decidiu mostrar todo seu talento e humor ao contar a fábula de uma irreverente vaca chamada Elsie Bovary, que é também a narradora da história. A heroína quadrúpede tem uma revelação na casa da fazenda onde vive que deixa seu mundo de cabeça para baixo. Elsie convence um porco e um peru a fugirem dali em busca de um mundo mais seguro. Daí segue uma sequência hilária que envolve passaportes falsos, bichos disfarçados de seres humanos e personagens espirituosos que falam sobre aceitação entre seres de espécies diferentes."),
("Quanto Mais Conheço os Homens, Mais Gosto do Meu Cão", "Olivia Edward", "Bizâncio", "Comédia", "Os cães são melhores do que os homens. É óbvio! São mais baratos e mais fáceis de contentar. Estão sempre encantados por a verem, são leais até ao fim e não se ralam quando ganha uns quilitos.Um cachorro felpudo ou um tipo cervejudo? A escolha, meninas é vossa."),
("Livro Somos (Mesmo) uma Merda a Crescer", "Filipa Beleza", "Penguin", "Comédia", "Amor, ansiedade, redes sociais, trabalho, crescer. Filipa Beleza pegou nas grandes questões da humanidade: Instagram, ansiolíticos, sexo e empregos precários, e deu-lhes a sua voz, cheia de humor, raiva, frustração e algumas lágrimas. e ainda as ilustrou. O resultado é este livro que pode muito bem ser a voz de uma geração. Ou uma bela foto no Instagram."),
("Odeio O Meu Chefe", "Filipa Fonseca", "Bertrand Editora", "Comédia", "Toda a gente já teve um mau chefe. Trata-se de um dado adquirido. Uma lei universal para quem entra no mercado de trabalho desde os primórdios da existência de qualquer mercado de trabalho.»Odeias o teu chefe? Já adormeceste a pensar em maneiras de fazê-lo desaparecer sem deixar rasto? Então, este livro é para ti. Tendo por ponto de partida histórias totalmente reais, umas vividas pela autora ao longo de vários anos a trabalhar por conta de outrem, outras confidenciadas pelos seus próprios leitores, Filipa Fonseca Silva traz-nos um retrato hilariante do pequeno poder. Com a escrita sarcástica a que já nos habituou, agora acompanhada por ilustrações da sua autoria, Filipa expõe ao ridículo todos os maus chefes, na esperança de que sintam algum pudor na próxima vez que tentarem ser umas bestas. Catártico, certeiro, acutilante."),
("A hipótese do amor", "Ali Hazelwood", "Arqueiro", "Comédia", "Olive Smith, aluna do doutorado em Biologia da Universidade Stanford, acredita na ciência – não em algo incontrolável como o amor. Depois de sair algumas vezes com Jeremy, ela percebe que sua melhor amiga gosta dele e decide juntá-los. Para mostrar que está feliz com essa escolha, Olive precisa ser convincente: afinal, cientistas exigem provas. Sem muitas opções, ela resolve inventar um namoro de mentira e, num momento de pânico, beija o primeiro homem que vê pela frente. O problema é que esse homem é Adam Carlsen, um jovem professor de prestígio – conhecido por levar os alunos às lágrimas. Por isso, Olive fica chocada quando o tirano dos laboratórios concorda em levar adiante a farsa e fingir ser seu namorado. De repente, seu pequeno experimento parece perigosamente próximo da combustão e aquela pequena possibilidade científica, que era apenas uma hipótese sobre o amor, transforma-se em algo totalmente inesperado.");

INSERT INTO livros 
(titulo, autor, editora, genero, sinopse)

VALUES

("O Diário de Anne Frank", "Anne Frank", "Pe Da Letra", "Drama", "Escrito entre 12 de junho de 1942 e 1 de agosto de 1944, O Diário de Anne Frank foi publicado pela primeira vez em 1947, por iniciativa de seu pai, revelando ao mundo o dia a dia de dois longos anos de uma adolescente forçada a esconder-se, juntamente com a sua família e um grupo de outros judeus, durante a ocupação nazi da cidade de Amesterdão. Todos os que se encontravam naquele pequeno anexo secreto acabaram por ser presos em agosto de 1944, e em março de 1945 Anne Frank morreu no campo de concentração de Bergen-Belsen, a escassos dois meses do final da guerra na Europa. O seu diário tornar-se-ia um dos livros de não ficção mais lidos em todo o mundo, testemunho incomparável do terror da guerra e do fulgor do espírito humano."),
("O menino do pijama listrado", "John Boyne", "Seguinte", "Drama", "Bruno tem nove anos e não sabe nada sobre o Holocausto e a Solução Final contra os judeus. Também não faz idéia que seu país está em guerra com boa parte da Europa, e muito menos que sua família está envolvida no conflito. Na verdade, Bruno sabe apenas que foi obrigado a abandonar a espaçosa casa em que vivia em Berlim e a mudar-se para uma região desolada, onde ele não tem ninguém para brincar nem nada para fazer. Da janela do quarto, Bruno pode ver uma cerca, e para além dela centenas de pessoas de pijama, que sempre o deixam com frio na barriga. Em uma de suas andanças Bruno conhece Shmuel, um garoto do outro lado da cerca que curiosamente nasceu no mesmo dia que ele. Conforme a amizade dos dois se intensifica, Bruno vai aos poucos tentando elucidar o mistério que ronda as atividades de seu pai. O menino do pijama listrado é uma fábula sobre amizade em tempos de guerra, e sobre o que acontece quando a inocência é colocada diante de um monstro terrível e inimaginável."),
("Anos de chumbo e outros contos", "Chico Buarque", "Companhia das Letras", "Drama", "Uma jovem e seu tio. Um grande artista sabotado. Um desatino familiar. Uma moradora de rua solitária. Um passeio por Copacabana. Um fã fervoroso de Clarice Lispector. Um casal em sua primeira viagem. Um lar em guerra. Imersos na elogiada atmosfera da ficção de Chico Buarque, caracterizada pela agudeza da observação e a oposição frequente entre o poético e o cômico, os oito contos que formam este volume conduzem o leitor pela sordidez e o patético da condição humana. Com alusões ocasionais à barbárie do presente, o autor ergue um labirinto de surpresas, em que o sexo, a perversidade, o desalento e o delírio são elementos constitutivos da trama. Em Anos de chumbo, Chico Buarque põe seu conhecido domínio da linguagem a serviço da concisão da forma. O resultado é arrebatador."),
("A cabana", "William P. Young", "Arqueiro", "Drama", "Durante uma viagem de fim de semana, a filha mais nova de Mack Allen Phillips é raptada e evidências de que ela foi brutalmente assassinada são encontradas numa velha cabana. Após quatro anos vivendo numa tristeza profunda causada pela culpa e pela saudade da menina, Mack recebe um estranho bilhete, aparentemente escrito por Deus, convidando-o a voltar à cabana onde acontecera a tragédia. Apesar de desconfiado, ele vai ao local numa tarde de inverno e adentra passo a passo o cenário de seu mais terrível pesadelo. Mas o que ele encontra lá muda o seu destino para sempre. Em um mundo cruel e injusto, A cabana levanta um questionamento atemporal: se Deus é tão poderoso, por que não faz nada para amenizar nosso sofrimento? As respostas que Mack encontra vão surpreender você e podem transformar sua vida de maneira tão profunda quanto transformaram a dele. Você vai querer partilhar esse livro com todas as pessoas que ama."),
("A travessia", "William P. Young", "Arqueiro", "Drama", "Um derrame cerebral deixa Anthony Spencer, um multimilionário egocêntrico, em coma. Quando acorda, ele se vê em um mundo surreal habitado por um estranho, que descobre ser Jesus, e por uma idosa que é o Espírito Santo. À sua frente se descortina uma paisagem que lhe revela toda a mágoa e a tristeza de sua vida terrena. Jamais poderia ter imaginado tamanho horror. Debatendo-se contra um sofrimento emocional insuportável, ele implora por uma segunda chance. Sua prece é ouvida e ele é enviado de volta à Terra, onde viverá uma experiência de profunda comunhão com uma série de pessoas e terá a oportunidade de reexaminar a própria vida. Nessa jornada, precisará enxergar através dos olhos dos outros e conhecer suas visões de mundo, suas esperanças, seus medos e seus desafios. Na busca de redenção, Tony deverá usar um poder que lhe foi concedido: o de curar uma pessoa. Será que ele terá coragem de fazer a escolha certa?"),
("A cidade do sol", "Khaled Hosseini", "Globo Livros", "Drama", "Do relacionamento proibido entre um rico comerciante de uma das maiores cidades do Afeganistão e uma de suas empregadas nasce Mariam, uma jovem marcada pelo ostracismo e a tragédia que, rejeitada pelo pai, vive em um casebre na periferia com a mãe, tendo como único passatempo, além dos afazeres domésticos, observar os mosquitos, as flores e as pedras. Ainda adolescente, perde a mãe e é obrigada a se casar com um desconhecido trinta anos mais velho e cumprir o seu dever como mulher: servir ao marido e lhe dar muitos filhos. O destino, entretanto, parece ter outros planos para Mariam, assim como para seu país. 1993, Cabul. Laila tem catorze anos. Filha de um intelectual, ela cresceu sendo incentivada a estudar, cursar uma universidade, ter uma carreira e só depois, se assim o desejasse, pensar em se casar. Entretanto, quando seus dois irmãos são enviados para lutar contra os soviéticos, a mãe passa a ignorála e a se isolar em sua tristeza. Laila se vê então obrigada a assumir as responsabilidades da casa, enquanto tenta manter sua rotina na escola, seus encontros com as amigas e sua paixão secreta pelo vizinho. Laila havia sido criada para ser quem ela quisesse, entretanto, logo a guerra irá lhe mostrar que nem sempre seus desejos podem se tornar realidade. Mariam e Laila são duas mulheres com idades, trajetórias e origens opostas que acabam unidas pelas tragédias da guerra e as restrições impostas pelo talibã. Seus destinos se cruzam de forma inexorável, e elas, em todas as suas diferenças, se provarão como suas únicas fontes de alegria, amizade e esperança. Ambas representam uma legião de mulheres afegãs que lutam todos os dias pela garantia de seus direitos mais básicos e por pequenos momentos de felicidade."),
("O caçador de pipas", "Khaled Hosseini", "Globo Livros", "Drama", "'O caçador de pipas' conta a história de Amir, um afegão há muito imigrado para os Estados Unidos, que se vê obrigado a acertar as contas com o passado e retorna a seu país de origem. O ponto de partida do livro é a infância do protagonista, quando Cabul ainda não era a capital do país que foi invadido pela União Soviética, dominado pelos talibãs e subjugado pelos Estados Unidos."),
("É Assim que Acaba", "Colleen Hoover", "Galera", "Drama", "Em É assim que acaba, Colleen Hoover nos apresenta Lily, uma jovem que se mudou de uma cidadezinha do Maine para Boston, se formou em marketing e abriu a própria floricultura. E é em um dos terraços de Boston que ela conhece Ryle, um neurocirurgião confiante, teimoso e talvez até um pouco arrogante, com uma grande aversão a relacionamentos, mas que se sente muito atraído por ela. Quando os dois se apaixonam, Lily se vê no meio de um relacionamento turbulento que não é o que ela esperava. Mas será que ela conseguirá enxergar isso, por mais doloroso que seja? É assim que acaba é uma narrativa poderosa sobre a força necessária para fazer as escolhas certas nas situações mais difíceis. Considerada a obra mais pessoal de Hoover, o livro aborda sem medo alguns tabus da sociedade para explorar a complexidade das relações tóxicas, e como o amor e o abuso muitas vezes coexistem em uma confusão de sentimentos.");

INSERT INTO livros 
(titulo, autor, editora, genero, sinopse)

VALUES

("Fahrenheit 451", "Ray Bradbury", "11 X 17", "Ficção Científica", "Guy Montag é um bombeiro. O seu emprego consiste em destruir livros proibidos e as casas onde esses livros estão escondidos. Ele nunca questiona a destruição causada, e no final do dia regressa para a sua vida apática com a esposa, Mildred, que passa o dia imersa na televisão. Um dia, Montag conhece a sua excêntrica vizinha Clarisse e é como se um sopro de vida o despertasse para o mundo. Ela apresenta-o a um passado onde as pessoas viviam sem medo e dá-lhe a conhecer ideias expressas em livros. Quando conhece um professor que lhe fala de um futuro em que as pessoas podem pensar, Montag apercebe-se subitamente do caminho de dissensão que tem de seguir. Mais de sessenta anos após a sua publicação, o clássico de Ray Bradbury permanece como uma das contribuições mais brilhantes para a literatura distópica e ainda surpreende pela sua audácia e visão profética.Guy Montag é um bombeiro. O seu emprego consiste em destruir livros proibidos e as casas onde esses livros estão escondidos. Ele nunca questiona a destruição causada, e no final do dia regressa para a sua vida apática com a esposa, Mildred, que passa o dia imersa na televisão. Um dia, Montag conhece a sua excêntrica vizinha Clarisse e é como se um sopro de vida o despertasse para o mundo. Ela apresenta-o a um passado onde as pessoas viviam sem medo e dá-lhe a conhecer ideias expressas em livros. Quando conhece um professor que lhe fala de um futuro em que as pessoas podem pensar, Montag apercebe-se subitamente do caminho de dissensão que tem de seguir. Mais de sessenta anos após a sua publicação, o clássico de Ray Bradbury permanece como uma das contribuições mais brilhantes para a literatura distópica e ainda surpreende pela sua audácia e visão profética."),
("Duna", "Frank Herbert", "Relógio D'Água", "Ficção Científica", "Obra-prima de Frank Herbert, Duna decorre no planeta deserto de Arrakis. Narra a história de Paul Atreides, herdeiro de uma família nobre encarregada de governar um mundo inóspito, onde a única coisa de valor é uma especiaria, melange, que é na verdade uma droga capaz de prolongar a vida e expandir a consciência. Cobiçada em todo o universo conhecido, a melange revela-se um tesouro pelo qual as pessoas estão dispostas a matar."),
("Filhos de Duna", "Frank Herbert", "Relógio D'Água", "Ficção Científica", "Os Filhos de Duna são os irmãos gémeos Leto e Ghanima Atreides, cujo pai, o Imperador Paul Muad’Dib, desapareceu nos terrenos baldios do deserto de Arrakis há nove anos. Tal como o pai, os gémeos possuem habilidades excecionais, o que os torna valiosos para a sua tia Alia, uma mulher manipuladora que governa o Império em nome da Casa Atreides. Enfrentando uma traição e rebeliões em duas frentes, o poder de Alia não é absoluto, e a excomungada Casa Corrino planeia uma forma de reconquistar o trono enquanto os Fremen são incitados à revolta pela enigmática figura conhecida apenas como O Pregador. Alia acredita que só acedendo à visão profética dos gémeos poderá manter o controlo sobre a sua dinastia. Mas Leto e Ghanima têm os seus próprios planos, tanto para as suas visões, como para os seus destinos."),
("O Messias de Duna", "Frank Herbert", "Relógio D'Água", "Ficção Científica", "O Messias de Duna continua a história de Paul Atreides em Duna. Em doze anos de Guerra Santa, ele venceu os inimigos e os seus Fremen conquistaram o universo. Atreides tornou-se o imperador Muad’Dib. É quase um deus, pois é capaz de ver o futuro. Conhece os inimigos que conspiram contra ele e sabe como tencionam atacá-lo. É capaz de derrotar os seus planos, mas vê mais longe ainda. Sabe que alguns futuros prováveis podem levar ao desastre e que o caminho para a liberdade enfrenta inúmeros perigos, podendo talvez exigir o seu sacrifício."),
("Ruination", "Anthony Reynolds", "Nuvem de Tinta", "Ficção Científica", "O primeiro livro ambientado no universo de league of legends, um dos videojogos mais populares de sempre. Quando o tio de Kalista, o jovem e narcisista Viego, se torna rei, ela promete moderar os seus instintos destrutivos, tornando-se sua leal confidente, conselheira e general militar. No entanto, Kalista vê os seus desígnios gorados quando a lâmina envenenada de um assassino atinge a esposa de Viego, Isolde, contagiando-a com uma doença incurável. À medida que o estado de Isolde piora, Viego desce à loucura e à dor, ameaçando arrastar Camavor consigo. É então que Kalista tenta uma jogada desesperada para salvar o reino, lançando-se em busca das Ilhas Abençoadas. As ilhas, há muito desaparecidas, poderão ser a chave para a salvação da rainha — isto é, se Kalista conseguir encontrá-las. A corrupção cresce na capital das Ilhas Abençoadas, onde um guardião vingativo procura enredar Kalista nas suas cruéis intrigas. Ela será forçada a escolher entre a sua lealdade a Viego e fazer o que ela sabe que é certo… Porque, mesmo perante a escuridão absoluta, um gesto nobre pode acender a luz que salvará o mundo."),
("Ceifador", "Neal Shusterman", "Desrotina", "Ficção Científica", "Primeiro mandamento: matarás. A Humanidade conquistou todas as barreiras... até mesmo a morte. Agora, os Ceifadores são os únicos que podem pôr fim a uma vida, e é-lhes ordenado que o façam, a fim de manter o crescimento da população sob controlo. Citra e Rowan são escolhidos como aprendizes de Ceifador — um cargo que nenhum deles quer, mas que terão de desempenhar para não perderem a sua própria vida. Porém, algo corre terrivelmente mal, e Citra e Rowan veem-se um contra o outro, num jogo perigoso em que só um pode ganhar. Ceifador é o primeiro livro de uma emocionante série do autor vencedor do National Book Award, Neal Shusterman, na qual Citra e Rowan aprendem que um mundo perfeito só existe quando se paga um preço muito elevado."),
("Robopocalipse", "Daniel H. Wilson", "Bertrand", "Ficção Científica", "Num futuro não muito longínquo, a espantosa tecnologia que gere o nosso mundo vira-se contra nós. Controlada por uma inteligência artificial infantil, mas extremamente poderosa, chamada Archos, a rede global de máquinas de que o nosso mundo se tornou dependente transforma-se de repente num inimigo implacável e mortal. Na hora H, o momento em que os robôs atacam, a espécie humana é quase completamente erradicada, mas, à medida que os sobreviventes se começam a reagrupar, a humanidade une-se pela primeira vez num esforço concertado de resistência. Este é o relato oral do conflito, contado por um elenco internacional de sobreviventes que viveram na pele este confronto longo e sangrento com as máquinas. Robopocalipse é um épico brilhante, cheio de ação e de pormenores ricos, com implicações arrepiantes no que diz respeito à tecnologia que nos rodeia."),
("As Primeiras Quinze Vidas de Harry August", "Claire North", "Saída de Emergência", "Ficção Científica", "Harry August não é um homem normal. Porque os homens normais, quando a morte chega, não regressam novamente ao dia em que nasceram, para voltarem a viver a mesma vida mas mantendo todo o conhecimento das vidas anteriores. Não interessa que feitos alcança, decisões toma ou erros comete, Harry já sabe que quando morrer irá tudo voltar ao início. Mas se este acumular de experiências e conhecimento podem fazer dele um quase semideus, algo continua a atormentar Harry: qual a origem do seu dom e será que há mais pessoas como ele? A resposta para ambas as perguntas parece chegar aquando da sua décima primeira morte, com a visita de uma menina que lhe traz uma mensagem: o fim do mundo aproxima-se. Esta é a história do que Harry faz a seguir, do que fez anteriormente, e ainda de como tenta salvar um passado que não consegue mudar e um futuro que não pode deixar que aconteça."),
("Limite", "Frank Schatzing", "Dom Quixote", "Ficção Científica", "Maio de 2025: o fornecimento energético da Terra parece estar assegurado, desde que os Estados Unidos começaram a extrair Hélio-3 da Lua. As tecnologias pioneiras da corporação gigante Orley Enterprises revolucionaram a aeronáutica; americanos e chineses disputam direitos de exploração numa renhida corrida espacial. A ação transporta-nos para o meio das tumultuosas guerras mercenárias africanas, uma contenda pelo petróleo e energias alternativas, onde imperam ambições de domínio espacial - acabando depois na Lua, onde um grupo de viajantes de Orley se vê subitamente confrontado com uma ameaça mortífera."),
("Neuromancer", "William Gibson", "Edições Asa", "Ficção Científica", "Quando oferecem a Case, um cowboy hacker em autodestruição, a oportunidade de voltar para o ciberespaço e para a matrix, ele aceita sem hesitar. Estará ele pronto para enfrentar todas as consequências? Preparado para lidar com um inimigo muito mais inteligente e mais forte que ele? Acompanhado por Molly, uma samurai de olhos espelhados, e Armitage, um veterano da guerra contra os soviéticos, Case vai ter de ultrapassar obstáculos inimagináveis, tanto no mundo real como na matrix. Neuromancer foi o primeiro vislumbre do que seria o futuro digital da humanidade - uma visão chocante que desafiou as nossas suposições sobre tecnologia e acerca de nós mesmos. Reinventou a forma como falamos e até como pensamos e alterou para sempre a paisagem da nossa imaginação. Sendo considerada uma obra-prima da ficção científica."),
("2001: Odisseia no Espaço", "Arthur C. Clarke", "Saída de Emergência", "Ficção Científica", "Estamos no início do século XXI e a Discovery viaja a cento e cinquenta mil quilómetros por hora no espaço. A bordo da nave espacial viajam navegadores, astronautas e Hal, um supercomputador cujo funcionamento cognitivo rivaliza com a mente humana. No entanto, a missão é ameaçada quando Hal começa a falhar. Será um problema técnico? E que influência tem o monólito encontrado na Lua? Com estas perguntas surgem outras: que lugar ocupa o Homem na complexa estrutura do infinito? O que é o tempo, a vida, a morte? 2001: Odisseia no Espaço é uma viagem espacial de tirar o fôlego na busca por evidências de que o ser humano não está sozinho no cosmos. Uma expedição aos confins do Universo e da alma, na qual passado, presente e futuro se mesclam num contínuo enigmático. Um extraordinário romance épico, com um amplo leque de interpretações e que permanece como um dos grandes clássicos da ficção científica."),
("A Conspiração de Atlântida", "R. C. Colaço", "Cultura Editora", "Ficção Científica", "A Conspiração de Atlântida posiciona Portugal como uma das federações mais importantes do mundo no século XXXI, relembrando o imaginário da época dos descobrimentos dos séculos XV e XVI. Nos séculos XXX e XXXI a Federação Lusitana desenvolve uma tecnologia de plataformas oceânicas que possibilita a produção de energia inesgotável, sem poluição e infindável. Preocupações atuais como a dependência energética de combustíveis fósseis, a subida do nível do mar e o impacto que a tecnologia tem nas relações humanas fundem-se numa história que revela possibilidades, soluções e riscos que o futuro apresenta, deixando o leitor a refletir sobre o que é ficção e o que já faz parte do quotidiano. O autor revela uma imaginação fantástica e minuciosa que nos transporta ao futuro, possibilitando uma análise e reflexão únicas sobre o presente e as possíveis consequências do progresso tecnológico."),
("Um estranho numa Terra estranha", "Robert A. Heilein", "Saída de Emergência", "Ficção Científica", "Há vinte e cinco anos, a primeira missão a Marte terminou em tragédia e todos os tripulantes morreram. Mas, na verdade, houve um sobrevivente. Nascido na fatídica nave espacial e salvo pelos Marcianos que o criaram e lhe ofereceram uma nova vida, Valentine Michael Smith nunca viu um ser humano até ao dia em que é descoberto por uma segunda expedição a Marte. Ao regressar à Terra, vê-se pela primeira vez entre o seu povo. Começa então um percurso de aprendizagem dos códigos sociais e preconceitos da natureza humana, totalmente alienígenas para a sua mente. Nesse processo de descoberta e integração, Valentine irá partilhar com a Humanidade os rituais sagrados que aprendeu em Marte e retribuir com as suas próprias crenças sobre o amor e o sentido da vida. Mas conseguirá alguma vez deixar de se sentir um estranho numa terra estranha?"),
("A História de Uma Serva", "Margaret Atwood", "Bertrand Editora", "Ficção Científica", "Uma visão marcante da nossa sociedade radicalmente transformada por uma revolução teocrática. 'A História de Uma Serva' tornou-se um dos livros mais influentes e mais lidos do nosso tempo. Extremistas religiosos de direita derrubaram o governo norteamericano e queimaram a Constituição. A América é agora Gileade, um estado policial e fundamentalista onde as mulheres férteis, conhecidas como Servas, são obrigadas a conceber filhos para a elite estéril. Defred é uma Serva na República de Gileade e acaba de ser transferida para a casa do enigmático Comandante e da sua ciumenta mulher. Pode ir uma vez por dia aos mercados, cujas tabuletas agora são imagens, porque as mulheres estão proibidas de ler. Tem de rezar para que o Comandante a engravide, já que, numa época de grande decréscimo do número de nascimentos, o valor de Defred reside na sua fertilidade, e o fracasso significa o exílio nas Colónias, perigosamente poluídas. Defred lembra-se de um tempo em que vivia com o marido e a filha e tinha um emprego, antes de perder tudo, incluindo o nome. Essas memórias misturam-se agora com ideias perigosas de rebelião e amor."),
("Eu, Robô", "Isaac Asimov", "Relógio D'Água", "Ficção Científica", "Publicado em 1950, Eu, Robô tornou-se um clássico da ficção científica. Nesta obra, Isaac Asimov fala-nos do desenvolvimento dos robôs, começando com a relação entre um deles e uma rapariga que o trata como um companheiro de brincadeiras. Mas é aqui que enuncia aquelas que ainda hoje são consideradas as três leis fundamentais da robótica do ponto de vista humano. Essas normas são: — um robô não pode ferir um ser humano ou permitir que ele sofra; — um robô deve obedecer às ordens que lhes são dadas por seres humanos, exceto nos casos em que entram em conflito com a necessidade de não lhes causar qualquer mal; — um robô deve proteger a sua própria existência, desde que não entre em conflito as duas primeiras leis."),
("Será que os Androides Sonham com Ovelhas Elétricas?", "Philip K. Dick", "Relógio D'Água", "Ficção Científica", "Philip K. Dick morreu em 1982, mas a sua visão futurista, carregada de humor negro, é mais perturbante e poderosa do que nunca. A Guerra deixou a Terra devastada. Por entre as ruínas, o caçador de recompensas Rick Deckard persegue a sua presa: os andróides desertores. Quando não desempenha esta tarefa, Deckard sonha possuir o maior símbolo de status da época: um animal vivo. É então que Rick recebe a sua principal tarefa: localizar seis Nexus, seis alvos que lhe podem valer uma enorme recompensa. Mas a vida nunca é assim tão linear, e a de Rick transforma-se rapidamente num pesadelo caleidoscópio de subterfúgios e enganos."),
("O Homem do Castelo Alto", "Philip K. Dick", "Relógio D'Água", "Ficção Científica", "América, quinze anos após o final da Segunda Grande Guerra. As potências vencedoras dividiram as suas conquistas: os nazis controlam Nova Iorque e a Califórnia é controlada por Japoneses. Mas entre estes dois estados confrontados numa guerra fria existe uma zona neutra onde, dizem os rumores, reside o lendário autor Hawthorne Abendsen, que receia pela sua vida, pois escreveu em tempos um livro no qual os aliados venceram a Segunda Grande Guerra.");


INSERT INTO pedido

(livro, genero, nome, email)

VALUES ("Spoiler Alert", "Comédia", "Milena", "milenapedido@gmail.com"),
("Depois que o Brasil Acabou", "Comédia", "Joseane"),
("Saboroso Cadáver", "Thriller", "Railan", "railanpedido@gmail.com");

INSERT INTO comentario

(livro_titulo, nome, comentario, email)

VALUES

("It: A coisa", "Railan", "Já li alguns livros do King e a maior parte dos calhamaços dele e sou fascinada pela escrita do autor. Tirando a cena x que é melhor ser ignorada o livro é todo sensacional, existem alguns momentos que ele se prolonga demais, mas quando se termina o livro fica aquela sensação de ter vivido em Derry mesmo, li aos poucos, demorando 2 semanas e consegui aproveitar bem a leitura", "railan@gmail.com"),
("Uma mulher no escuro", "Milena", "Um excelente livro.", "milena@gmail.com");

SELECT * FROM livros;

SELECT * FROM pedido;
    
